- .travis.swagger.sh
Check on the consumer side is made also here https://github.com/hawkular/hawkular.github.io/blob/pages/.travis.swagger.sh#L23
> don't push empty REST documentation

- tests/client-camel/pom.xml
Reverts hawkular/hawkular-btm#41
> Revert "Stop camel tests being executed in parallel"

- client/btxn-instrumentation/src/main/resources/btmconfig/javax/btm-javax-jms.json
Found when testing against ActiveMQ in EAP.
> HWKBTM-197 Further work to prevent JMS send for temp queue

- ui/src/main/scripts/plugins/apm/ts/apm.ts
When some previously reported values are missing from reported values,
it causes the chart to fail to draw. This fixes it by adding a 0 value
to missing entries.
> HWKBTM-331 : Fix APM chart when missing entries

- ui/src/main/scripts/plugins/apm/html/apm.html
- ui/src/main/scripts/plugins/apm/ts/apm.ts
Also some UI enhancements to the APM controls and a fix to make the APM
chart "empty" when there's no more data instead of showing last data.
> Toggle between stacked or layered data @ APM chart

- ui/src/main/scripts/plugins/btm/html/btm.html
- ui/src/main/scripts/plugins/btm/ts/btm.ts
This fixes the pie chart not showing and resizing to several forms. This
is due to non-angular lib with angular hide/show of parent element. An
extra variable is observed to know that data is already available.
> HWKBTM-333 : Fix pie chart not displaying at first

- ui/src/main/scripts/plugins/btm/html/btxnignored.html
- ui/src/main/scripts/plugins/btm/ts/btxnignored.ts
- Add "No ignored BTxns" slate panel;
- Fix Loader;
- Add "No matching filter" slate panel;
- Match filter input style with Managed;
- Other internal fixes & alignments with Managed tab
> HWKBTM-346 : Improve UI for Ignored BTxns

- ui/src/main/scripts/plugins/apm/ts/apm.ts
- ui/src/main/scripts/plugins/apm/ts/apmGlobals.ts
- ui/src/main/scripts/plugins/apm/ts/apmPlugin.ts
- ui/src/main/scripts/plugins/btm/ts/btm.ts
- ui/src/main/scripts/plugins/btm/ts/btmGlobals.ts
- ui/src/main/scripts/plugins/btm/ts/btmPlugin.ts
- ui/src/main/scripts/plugins/btm/ts/btxncandidates.ts
- ui/src/main/scripts/plugins/btm/ts/btxnconfig.ts
- ui/src/main/scripts/plugins/btm/ts/btxnignored.ts
- ui/src/main/scripts/plugins/btm/ts/btxninfo.ts
- ui/src/main/scripts/tslint.json
Updated to latest Hawkular tslint.json and updated outstanding errors.
> HWKBTM-322 : Update tslint.json and fix problems

- ui/src/main/scripts/plugins/btm/ts/btxninfo.ts
Properties retrieval wasn't considering start and end time parameters.
> HWKBTM-364 : Update props list on time range change

- ui/src/main/scripts/plugins/btm/html/btxninfo.html
Show "No Data Available" on BTM Info Faults and Properties panels when
there's no data available to show.
> HWKBTM-372 : Show "No Data Available" on BTM Info

- ui/src/main/scripts/plugins/apm/html/apm.html
- ui/src/main/scripts/plugins/apm/ts/apm.ts
- ui/src/main/scripts/plugins/directives/filter-sidebar/html/filter-sidebar.html
- ui/src/main/scripts/plugins/directives/filter-sidebar/ts/filterSidebarDirective.ts
- ui/src/main/scripts/plugins/directives/filter-sidebar/ts/filterSidebarGlobals.ts
- ui/src/main/scripts/plugins/directives/filter-sidebar/ts/filterSidebarPlugin.ts
- ui/src/main/scripts/plugins/e2e/html/e2e.html
- ui/src/main/scripts/plugins/e2e/ts/e2e.ts
- Replace individual sidebars with angular directive;
- Make the filter criteria global (persists across tab navigation);
- Integrate "Time Span" into sidebar filtering;
- Make filtering functional in Dist. Tracing tab (where applicable);
> Make the filter sidebar a directive + enhancements

- ui/src/main/scripts/plugins/directives/dagre-d3/ts/dagreD3Directive.ts
- ui/src/main/scripts/plugins/e2e/html/e2e.html
- ui/src/main/scripts/plugins/e2e/ts/e2e.ts
Use the tree format in order to get nodes arranged in a tree structure
from the server side, instead of arranging them on the client side.
> HWKBTM-429 : Use tree format in UI for DT screen

- ui/src/main/scripts/plugins/apm/less/apm.less
- ui/src/main/scripts/plugins/apm/ts/apm.ts
- ui/src/main/scripts/plugins/directives/filter-sidebar/html/filter-sidebar.html
- ui/src/main/scripts/plugins/directives/filter-sidebar/less/filter-sidebar.less
- ui/src/main/scripts/plugins/directives/filter-sidebar/ts/filterSidebarDirective.ts
- ui/src/main/scripts/plugins/directives/filter-sidebar/ts/filterSidebarPlugin.ts
- ui/src/main/scripts/plugins/e2e/ts/e2e.ts
Initial commit for adding property and failt filtering to the sidebar.
This enables the APM and DT tabs to be make use of it.
> HWKBTM-350 & HWKBTM-351 Prop/Fault Filtering @ SB

- dist/src/main/scripts/distro-assembly.xml
Keep the unzipped distribution in target directory. 
@objectiser could you please review and eventually merge?
> Keep the unzipped distribution in target directory

- api/src/main/java/org/hawkular/apm/api/internal/actions/AddContentActionHandler.java
- api/src/main/java/org/hawkular/apm/api/internal/actions/EvaluateURIActionHandler.java
- api/src/main/java/org/hawkular/apm/api/internal/actions/SetDetailActionHandler.java
- api/src/main/java/org/hawkular/apm/api/internal/actions/SetPropertyActionHandler.java
- api/src/main/java/org/hawkular/apm/api/internal/actions/helpers/JSON.java
- api/src/main/java/org/hawkular/apm/api/internal/actions/helpers/XML.java
- api/src/main/java/org/hawkular/apm/api/services/AbstractAnalyticsService.java
- api/src/main/java/org/hawkular/apm/api/services/Criteria.java
- api/src/main/java/org/hawkular/apm/api/utils/EndpointUtil.java
- client/analytics-service-rest-client/src/main/java/org/hawkular/apm/analytics/service/rest/client/AnalyticsServiceRESTClient.java
- client/collector/src/main/java/org/hawkular/apm/client/collector/DefaultTraceCollector.java
- client/collector/src/main/java/org/hawkular/apm/client/collector/internal/ProcessorManager.java
- client/collector/src/main/java/org/hawkular/apm/client/collector/internal/TraceReporter.java
- client/config-service-rest-client/src/main/java/org/hawkular/apm/config/service/rest/client/ConfigurationServiceRESTClient.java
- client/instrumenter/src/main/java/org/hawkular/apm/instrumenter/APMAgent.java
- client/trace-publisher-rest-client/src/main/java/org/hawkular/apm/trace/publisher/rest/client/TracePublisherRESTClient.java
- processors/fragmentcompletiontime-deriver/src/main/java/org/hawkular/apm/processor/fragmentcompletiontime/FragmentCompletionTimeDeriver.java
- processors/nodedetails-deriver/src/main/java/org/hawkular/apm/processor/nodedetails/NodeDetailsDeriver.java
- processors/notification-deriver/src/main/java/org/hawkular/apm/processor/notification/NotificationDeriver.java
- server/api/src/main/java/org/hawkular/apm/server/api/task/ProcessingUnit.java
- server/elasticsearch/src/main/java/org/hawkular/apm/server/elasticsearch/AnalyticsServiceElasticsearch.java
- server/elasticsearch/src/main/java/org/hawkular/apm/server/elasticsearch/ElasticsearchUtil.java
- server/rest/src/main/java/org/hawkular/apm/server/rest/RESTServiceUtil.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:S1155 - "Collection.isEmpty() should be used to test for emptiness".
You can find more information about the issue here: 
https://sonarqube.com/coding_rules#q=squid:S1155
> Fixing squid:S1155 - Collection.isEmpty() should be used to test for emptiness

- pom.xml
- server/api/src/main/java/org/hawkular/apm/server/api/services/SpanCache.java
- server/infinispan/pom.xml
- server/infinispan/src/main/java/org/hawkular/apm/server/infinispan/InfinispanSpanCache.java
- server/infinispan/src/test/java/org/hawkular/apm/server/infinispan/AbstractInfinispanTest.java
- server/infinispan/src/test/java/org/hawkular/apm/server/infinispan/InfinispanCommunicationDetailsCacheTest.java
- server/infinispan/src/test/java/org/hawkular/apm/server/infinispan/InfinispanSpanCacheTest.java
https://issues.jboss.org/browse/HWKAPM-526
> HWKAPM-526 | Span Cache and Infinispan Impl

- server/infinispan/pom.xml
https://issues.jboss.org/browse/HWKAPM-553
@jpkrohling Could you please review?
> HWKAPM-553 | excluding apache lucene from infinispan-query

- processors/zipkin/src/main/java/org/hawkular/apm/processor/zipkin/FragmentCompletionTimeDeriver.java
- processors/zipkin/src/main/java/org/hawkular/apm/processor/zipkin/NodeDetailsDeriver.java
- server/api/src/main/java/org/hawkular/apm/server/api/services/SpanCache.java
- server/api/src/main/java/org/hawkular/apm/server/api/utils/SpanUniqueIdGenerator.java
- server/api/src/test/java/org/hawkular/apm/server/api/utils/SpanUniqueIdGeneratorTest.java
- server/infinispan/src/main/java/org/hawkular/apm/server/infinispan/InfinispanSpanCache.java
- server/infinispan/src/test/java/org/hawkular/apm/server/infinispan/InfinispanSpanCacheTest.java
https://issues.jboss.org/browse/HWKAPM-543
> HWKAPM-543 | Need to identify spans by a unique id

- processors/zipkin/pom.xml
- processors/zipkin/src/main/java/org/hawkular/apm/processor/zipkin/FragmentCompletionTimeDeriver.java
- processors/zipkin/src/main/java/org/hawkular/apm/processor/zipkin/HttpCodesUtil.java
- processors/zipkin/src/main/java/org/hawkular/apm/processor/zipkin/NodeDetailsDeriver.java
- processors/zipkin/src/test/java/org/hawkular/apm/processor/zipkin/HttpCodesUtilTest.java
https://issues.jboss.org/browse/HWKAPM-520
> HWKAPM-520 | Set fault field based on HTTP status code in zipkin span

- server/jms/src/main/java/org/hawkular/apm/server/jms/span/SpanStoreMDB.java
https://issues.jboss.org/browse/HWKAPM-527
I tried to do some integration tests but Weld is complaining about Unsatisfied dependencies..
Here it is https://github.com/pavolloffay/hawkular-apm/blob/HWKAPM-527-MDB-for-storing-Spans-in-the-SpanService-arquillian/server/jms/src/test/java/org/hawkular/apm/server/jms/span/SpanStoreMDBTest.java
Note I have solved weld issues now elasticsearch is complaining. It can be merged if it is ok. I will try to finish arquilian test during the weekend.
> HWKAPM-527 | MDB for storing Spans in the SpanService

- ui/src/main/scripts/plugins/directives/instance-view-diagram/ts/instanceViewDiagramDirective.ts
- ui/src/main/scripts/plugins/directives/instance-view-diagram/ts/instanceViewDiagramGlobals.ts
- ui/src/main/scripts/plugins/directives/instance-view-diagram/ts/instanceViewDiagramPlugin.ts
- ui/src/main/scripts/plugins/e2e/html/details-modal.html
- ui/src/main/scripts/plugins/e2e/html/e2e.html
- ui/src/main/scripts/plugins/e2e/less/e2e.less
- ui/src/main/scripts/plugins/e2e/ts/e2e.ts
Adds a Details column to the Instance Details Table, which when clicked
shows a diagram depicting the nodes which compose the entry.
> Initial commit for Instance Details Diagram View

- server/elasticsearch/src/main/java/org/hawkular/apm/server/elasticsearch/SpanServiceElasticsearch.java
https://issues.jboss.org/browse/HWKAPM-563
+ fixed some log strings which were copied  from trace service..
> Revert change to throw exception on serialization failure in SpanStoreElasticsearch

- server/infinispan/src/main/java/org/hawkular/apm/server/infinispan/InfinispanSpanCache.java
> make span cache impl singleton

- processors/tracecompletiontime-deriver/src/test/java/org/hawkular/apm/processor/tracecompletiontime/TestCommunicationDetailsCache.java
- server/api/src/main/java/org/hawkular/apm/server/api/services/CommunicationDetailsCache.java
- server/infinispan/src/main/java/org/hawkular/apm/server/infinispan/InfinispanCommunicationDetailsCache.java
- server/infinispan/src/main/java/org/hawkular/apm/server/infinispan/InfinispanProducerInfoCache.java
- server/infinispan/src/main/java/org/hawkular/apm/server/infinispan/InfinispanSpanCache.java
- server/infinispan/src/test/java/org/hawkular/apm/server/infinispan/InfinispanCommunicationDetailsCacheTest.java
- server/infinispan/src/test/java/org/hawkular/apm/server/infinispan/InfinispanSpanCacheTest.java
https://issues.jboss.org/browse/HWKAPM-555
Review notes:
* PR assures that in each unit used cache is empty.
> HWKAMP-555 | Enable CommunicationDetailsCache api and implementation to return list for specified id

- api/src/main/java/org/hawkular/apm/api/model/PropertyType.java
- api/src/main/java/org/hawkular/apm/api/model/events/CompletionTime.java
- api/src/main/java/org/hawkular/apm/api/model/events/NodeDetails.java
- processors/zipkin/src/main/java/org/hawkular/apm/processor/zipkin/CommunicationDetailsDeriver.java
- processors/zipkin/src/main/java/org/hawkular/apm/processor/zipkin/FragmentCompletionTimeDeriver.java
- processors/zipkin/src/main/java/org/hawkular/apm/processor/zipkin/NodeDetailsDeriver.java
- processors/zipkin/src/main/java/org/hawkular/apm/processor/zipkin/TraceCompletionTimeDeriver.java
- server/api/src/main/java/org/hawkular/apm/server/api/model/zipkin/Endpoint.java
- server/api/src/main/java/org/hawkular/apm/server/api/model/zipkin/Span.java
- server/api/src/main/java/org/hawkular/apm/server/api/utils/AnnotationTypeUtil.java
- server/api/src/main/java/org/hawkular/apm/server/api/utils/ProducerInfoCacheUtil.java
https://issues.jboss.org/browse/HWKAPM-531
https://issues.jboss.org/browse/HWKAPM-522
> HWKAPM-531 HWKAPM-522 | Transfer appropriate binary properties into properties field of derived information

- processors/zipkin/src/main/java/org/hawkular/apm/processor/zipkin/FragmentCompletionTimeDeriver.java
- processors/zipkin/src/main/java/org/hawkular/apm/processor/zipkin/NodeDetailsDeriver.java
- processors/zipkin/src/main/java/org/hawkular/apm/processor/zipkin/SpanDeriverUtil.java
- processors/zipkin/src/main/java/org/hawkular/apm/processor/zipkin/SpanHttpDeriverUtil.java
- processors/zipkin/src/main/java/org/hawkular/apm/processor/zipkin/TraceCompletionTimeDeriver.java
- processors/zipkin/src/test/java/org/hawkular/apm/processor/zipkin/SpanHttpDeriverUtilTest.java
https://issues.jboss.org/browse/HWKAPM-533
> HWKAPM-533 | Add http method from Span to derived information objects

- server/api/src/main/java/org/hawkular/apm/server/api/utils/AnnotationTypeUtil.java
> NPE - null binary annotation type to text property type

- api/src/main/java/org/hawkular/apm/api/model/analytics/CommunicationSummaryStatistics.java
- api/src/main/java/org/hawkular/apm/api/services/internal/CommunicationSummaryTreeBuilder.java
Minor changes, just some perf. improvements.
> improve time complexity of CommucationSummaryTreeBuilder

- server/api/src/main/java/org/hawkular/apm/server/api/services/SpanService.java
- server/elasticsearch/src/main/java/org/hawkular/apm/server/elasticsearch/SpanServiceElasticsearch.java
- server/elasticsearch/src/main/java/org/hawkular/apm/server/elasticsearch/TraceServiceElasticsearch.java
- server/elasticsearch/src/test/java/org/hawkular/apm/server/elasticsearch/SpanServiceElasticsearchTest.java
https://issues.jboss.org/browse/HWKAPM-542
https://issues.jboss.org/browse/HWKAPM-541
https://issues.jboss.org/browse/HWKAPM-576
> HWKAPM-542 | HWKAPM-541 | HWKAPM-571 |Span service - trace fragment and end to end trace

- tests/instrumentation-framework/src/test/java/org/hawkular/apm/tests/dockerized/InstrumentationTest.java
@objectiser could you please review.
> Fail instrumentation framework test if there are any failures

- server/infinispan/src/main/java/org/hawkular/apm/server/infinispan/InfinispanSpanCache.java
- server/infinispan/src/test/java/org/hawkular/apm/server/infinispan/InfinispanSpanCacheTest.java
https://issues.jboss.org/browse/HWKAPM-576
> Span cache getChildren should not return server spans

- tests/instrumentation-framework/src/main/java/org/hawkular/apm/tests/dockerized/environment/AbstractDockerBasedEnvironment.java
- tests/server/mock/src/main/java/org/hawkular/apm/tests/server/ApmMockServer.java
> exit APM mock server only if was running

- api/src/main/java/org/hawkular/apm/api/model/Constants.java
- processors/zipkin/src/main/java/org/hawkular/apm/processor/zipkin/CommunicationDetailsDeriver.java
- processors/zipkin/src/main/java/org/hawkular/apm/processor/zipkin/FragmentCompletionTimeDeriver.java
- processors/zipkin/src/main/java/org/hawkular/apm/processor/zipkin/NodeDetailsDeriver.java
- processors/zipkin/src/main/java/org/hawkular/apm/processor/zipkin/TraceCompletionTimeDeriver.java
- server/api/src/main/java/org/hawkular/apm/server/api/utils/ProducerInfoUtil.java
- server/elasticsearch/src/main/java/org/hawkular/apm/server/elasticsearch/SpanServiceElasticsearch.java
https://issues.jboss.org/browse/HWKAPM-592
> Add service name to Properties of derived objects

- server/api/src/main/java/org/hawkular/apm/server/api/model/zipkin/Annotation.java
- server/api/src/main/java/org/hawkular/apm/server/api/model/zipkin/BinaryAnnotation.java
- server/api/src/main/java/org/hawkular/apm/server/api/model/zipkin/Endpoint.java
- server/api/src/main/java/org/hawkular/apm/server/api/model/zipkin/Span.java
- server/api/src/main/java/org/hawkular/apm/server/api/utils/zipkin/BinaryAnnotationMappingStorage.java
- server/api/src/main/java/org/hawkular/apm/server/api/utils/zipkin/MappingResult.java
- server/api/src/test/java/org/hawkular/apm/server/api/model/zipkin/SpanTest.java
- server/api/src/test/java/org/hawkular/apm/server/api/utils/zipkin/BinaryAnnotationMappingDeriverTest.java
- server/elasticsearch/src/test/java/org/hawkular/apm/server/elasticsearch/SpanServiceElasticsearchTest.java
https://issues.jboss.org/browse/HWKAPM-588
> Make span model serializable for use with infinispan cache

- .travis.install.maven.sh
- .travis.yml
- pom.xml
Do not merge yet!
Build time of this PR (new travis config):
14 min 2 sec
7 min 17s
Build time with old travis config:
22 min 21 sec
26 min 40 sec
23 min 48 sec
23 min 43 sec
25 min 4 sec
22 min 26 sec
> travis ubuntu trusty to speed up tests and enable integration tests

- README.adoc
- dist/src/main/resources/apm/setenv.sh
> readme documentation link

- README.adoc
@jpkrohling could you please review?
> readme, typos fixes

- api/src/main/java/org/hawkular/apm/api/model/events/CompletionTime.java
- dist/src/main/scripts/standalone.xsl
- processors/tracecompletiontime-deriver/src/main/java/org/hawkular/apm/processor/tracecompletiontime/TraceCompletionInformationInitiator.java
- processors/tracecompletiontime-deriver/src/main/java/org/hawkular/apm/processor/tracecompletiontime/TraceCompletionInformationProcessor.java
- processors/zipkin/pom.xml
- processors/zipkin/src/main/java/org/hawkular/apm/processor/zipkin/CompletionTimeDeriver.java
- processors/zipkin/src/main/java/org/hawkular/apm/processor/zipkin/CompletionTimeDeriverInitiator.java
- processors/zipkin/src/main/java/org/hawkular/apm/processor/zipkin/CompletionTimeProcessing.java
- processors/zipkin/src/main/java/org/hawkular/apm/processor/zipkin/CompletionTimeProcessingDeriver.java
- processors/zipkin/src/main/java/org/hawkular/apm/processor/zipkin/CompletionTimeProcessingPublisher.java
- processors/zipkin/src/main/java/org/hawkular/apm/processor/zipkin/CompletionTimeUtil.java
- processors/zipkin/src/main/java/org/hawkular/apm/processor/zipkin/FragmentCompletionTimeDeriver.java
- processors/zipkin/src/main/java/org/hawkular/apm/processor/zipkin/TraceCompletionTimeDeriver.java
- processors/zipkin/src/test/java/org/hawkular/apm/processor/zipkin/CompletionTimeProcessingDeriverTest.java
- server/api/src/main/java/org/hawkular/apm/server/api/model/zipkin/Span.java
- server/api/src/main/java/org/hawkular/apm/server/api/services/SpanCache.java
- server/api/src/test/java/org/hawkular/apm/server/api/utils/SourceInfoUtilTest.java
- server/infinispan/src/main/java/org/hawkular/apm/server/infinispan/InfinispanSpanCache.java
- server/infinispan/src/test/java/org/hawkular/apm/server/infinispan/InfinispanSpanCacheTest.java
- server/jms/src/main/java/org/hawkular/apm/server/jms/span/comletiontime/CompletionTimeProcessingInitiatorMDB.java
- server/jms/src/main/java/org/hawkular/apm/server/jms/span/comletiontime/CompletionTimeProcessingMDB.java
- server/jms/src/main/java/org/hawkular/apm/server/jms/span/comletiontime/CompletionTimeProcessingPublisherJMS.java
- server/jms/src/main/java/org/hawkular/apm/server/jms/span/comletiontime/TraceCompletionTimeMDB.java
https://issues.jboss.org/browse/HWKAPM-523
Review notes:
* we may discuss how to deal with retry mechanism for long run spans.
> HWKAMP-523 | Trace completion time for async spans

- dist/src/main/scripts/standalone.xsl
- pom.xml
- server/api/src/main/java/org/hawkular/apm/server/api/services/SpanCache.java
- server/api/src/test/java/org/hawkular/apm/server/api/utils/SourceInfoUtilTest.java
- server/infinispan/pom.xml
- server/infinispan/src/main/java/org/hawkular/apm/server/infinispan/InfinispanCommunicationDetailsCache.java
- server/infinispan/src/main/java/org/hawkular/apm/server/infinispan/InfinispanPropertyCache.java
- server/infinispan/src/main/java/org/hawkular/apm/server/infinispan/InfinispanSourceInfoCache.java
- server/infinispan/src/main/java/org/hawkular/apm/server/infinispan/InfinispanSpanCache.java
- server/infinispan/src/test/java/org/hawkular/apm/server/infinispan/AbstractInfinispanTest.java
- server/infinispan/src/test/java/org/hawkular/apm/server/infinispan/InfinispanCommunicationDetailsCacheTest.java
- server/infinispan/src/test/java/org/hawkular/apm/server/infinispan/InfinispanPropertyCacheTest.java
- server/infinispan/src/test/java/org/hawkular/apm/server/infinispan/InfinispanSpanCacheTest.java
https://issues.jboss.org/browse/HWKAPM-613
> HWKAPM-613 | Remove dependency on infinispan-query

- server/api/src/main/java/org/hawkular/apm/server/api/model/zipkin/Span.java
- server/api/src/test/java/org/hawkular/apm/server/api/model/zipkin/SpanTest.java
> Http URL mapping enhancement

- dist/src/main/resources/apm/setenv.sh
> Do not exit current shell if port parameter is missing

- README.adoc
> readme apm port binding

- dist/pom.xml
@objectiser could you please review? It is minor thing removes warning from build log.
> antrun use target not deprecated task

- examples/polyglot-zipkin/java-dropwizard/src/main/java/org/hawkular/apm/example/dropwizard/rest/UsersHandler.java
> removed port from ruby service path, zipkinB3Filter did not correctly match urls

- dist/src/main/resources/apm/setenv.sh
@objectiser could you please review? It can be useful for somebody.
> script setenv.sh agent logging level

- server/infinispan/src/main/java/org/hawkular/apm/server/infinispan/InfinispanCommunicationDetailsCache.java
- server/infinispan/src/main/java/org/hawkular/apm/server/infinispan/InfinispanSpanCache.java
https://issues.jboss.org/browse/HWKAPM-642
> HWKAPM-642 | Concurrent modification exception in zipkin completion time processing driver

- api/src/main/java/org/hawkular/apm/api/model/analytics/CommunicationSummaryStatistics.java
- server/elasticsearch/src/main/java/org/hawkular/apm/server/elasticsearch/AnalyticsServiceElasticsearch.java
- server/elasticsearch/src/test/java/org/hawkular/apm/server/elasticsearch/AnalyticsServiceElasticsearchTest.java
- ui/src/main/scripts/plugins/directives/dagre-d3/ts/dagreD3Directive.ts
- ui/src/main/scripts/plugins/e2e/less/e2e.less
- ui/src/main/scripts/plugins/e2e/ts/e2e.ts
https://issues.jboss.org/browse/HWKAPM-532
> HWKAPM-532 | Display service name in Distributed Tracing graph

- ui/src/main/scripts/plugins/btm/less/btm.less
- ui/src/main/scripts/plugins/directives/instance-view-diagram/ts/instanceViewDiagramDirective.ts
- ui/src/main/scripts/plugins/e2e/html/details-modal.html
- ui/src/main/scripts/plugins/e2e/ts/e2e.ts
- Moved the instance details table below the DT diagram;
- Clicking on the details icon the modal is shown with single trace instance
> HWKAPM-593 : Fix for large trace instance diagrams

- ui/src/main/scripts/plugins/e2e/html/e2e.html
- ui/src/main/scripts/plugins/e2e/less/e2e.less
> Make Distributed Tracing diagram have full height

- tests/dist/src/test/java/org/hawkular/apm/tests/dist/AbstractITest.java
- tests/dist/src/test/java/org/hawkular/apm/tests/dist/AnalyticsServiceITest.java
- tests/dist/src/test/java/org/hawkular/apm/tests/dist/ConfigurationServiceITest.java
- tests/dist/src/test/java/org/hawkular/apm/tests/dist/TraceCompletionTimeITest.java
- tests/dist/src/test/java/org/hawkular/apm/tests/dist/TraceServiceITest.java
- tests/dist/src/test/java/org/hawkular/apm/tests/dist/zipkin/SpanAnalyticsITest.java
- tests/dist/src/test/java/org/hawkular/apm/tests/dist/zipkin/SpanServiceITest.java
> wildfly itest package rename to dist

- ui/src/main/scripts/plugins/directives/instance-view-diagram/ts/instanceViewDiagramDirective.ts
- ui/src/main/scripts/plugins/e2e/less/e2e.less
Also includes some fixes & improvements to Instance View Diagram, plus styles cleanup in code.
> HWKAPM-672 - Fix some lines being "filled"

- ui/src/main/scripts/plugins/directives/instance-view-diagram/ts/instanceViewDiagramDirective.ts
Also adjust the labels and values  to match better how it's shown in
Distributed Tracing diagram.
> HWKAPM-663 : Add operation to Instance Diagram nodes

- ui/src/main/scripts/plugins/directives/instance-view-diagram/ts/instanceViewDiagramDirective.ts
- ui/src/main/scripts/plugins/e2e/less/e2e.less
> HWKAPM-662 : Add URI/Op to components along with icon

- examples/polyglot-zipkin/docker-compose.yml
> python service depends on kafka

- dist/src/main/resources/standalone/configuration/zipkin-binary-annotation-mapping.json
- server/elasticsearch/src/main/java/org/hawkular/apm/server/elasticsearch/SpanServiceElasticsearch.java
> add sql.query to node properties

- examples/polyglot-zipkin/js-express/app.js
- examples/polyglot-zipkin/js-express/package.json
https://issues.jboss.org/browse/HWKAPM-689
Review notes:
Run polyglot-zipkin example with createUser request, dropwizard service should be shown after the first request.
> HWKAPM-689 | zipkin example nodejs, versions update, sampler setting

- examples/polyglot-zipkin/README.adoc
- examples/polyglot-zipkin/js-express/app.js
@objectiser could you please review? When it is merged I will post reproducer to https://github.com/openzipkin/zipkin-js/issues/32.
It can be also related to this issue: https://github.com/openzipkin/zipkin-js/issues/33
> HWKAPM-689 | reproducer for missing client spans from nodejs app

- examples/polyglot-zipkin/python-pyramid/Dockerfile
- examples/polyglot-zipkin/python-pyramid/setup.py
@objectiser could you please review? It's just a minor thing.
> dependencies for python app should be loaded with setuptools

- examples/polyglot-zipkin/README.adoc
@objectiser could you please review? We were right it is better to separate these sections.
> polyglot demo readme: separate run applications and server

- examples/polyglot-zipkin/java-cassandra/Dockerfile
- examples/polyglot-zipkin/java-cassandra/README.adoc
https://issues.jboss.org/browse/HWKAPM-695
> HWKAPM-695 | Docker hub fails to build java-cassandra

- api/pom.xml
- api/src/main/java/org/hawkular/apm/api/model/events/CommunicationDetails.java
https://issues.jboss.org/browse/HWKAPM-706
> HWKAPM-706 | Remove dependency on hibernate-search-engine

- examples/polyglot-zipkin/README.adoc
- examples/polyglot-zipkin/ruby-rack/Gemfile.lock
https://issues.jboss.org/browse/HWKAPM-623
@objectiser could you please review? 
Review notes:
1. locally compile docker image for ruby app
2. run polyglot example
3. run request createUsers and roda/hello.
> HWKAPM-623 | ruby zipkin-tracer version update

- ui/src/main/scripts/plugins/e2e/html/details-modal.html
- ui/src/main/scripts/plugins/e2e/less/e2e.less
- ui/src/main/scripts/plugins/e2e/ts/e2e.ts
> HWKAPM-703 : Group properties by name in Instance Table

- ui/src/main/scripts/plugins/apm/html/apm.html
- ui/src/main/scripts/plugins/btm/html/btm.html
- ui/src/main/scripts/plugins/e2e/html/details-modal.html
- ui/src/main/scripts/plugins/e2e/ts/e2ePlugin.ts
Add an angular filter to convert from μs duration to human readable format.
> HWKAPM-602 : Create hkTime filter for durations

- tests/instrumentation-framework/src/main/java/org/hawkular/apm/tests/dockerized/TestScenarioRunner.java
- tests/instrumentation-framework/src/main/java/org/hawkular/apm/tests/dockerized/environment/DockerComposeExecutor.java
- tests/instrumentation-framework/src/main/java/org/hawkular/apm/tests/dockerized/environment/DockerImageExecutor.java
- tests/instrumentation-framework/src/main/java/org/hawkular/apm/tests/dockerized/model/TestEnvironment.java
- tests/instrumentation-framework/src/test/resources/testTicketMonsterDockerCompose/test.json
- tests/instrumentation-framework/src/test/resources/testTicketMonsterDockerImage/test.json
https://issues.jboss.org/browse/HWKAPM-729
@objectiser could you please review!
> HWKAPM-729 | Instrumentation test framework: add option to pull images.

- ui/src/main/scripts/plugins/directives/dagre-d3/ts/dagreD3Directive.ts
- ui/src/main/scripts/plugins/directives/dagre-d3/ts/dagreD3Plugin.ts
- ui/src/main/scripts/plugins/directives/instance-view-diagram/ts/instanceViewDiagramDirective.ts
- ui/src/main/scripts/plugins/directives/instance-view-diagram/ts/instanceViewDiagramPlugin.ts
- ui/src/main/scripts/plugins/e2e/ts/e2ePlugin.ts
Also enhance the duration filter to show μs as decimal ms and seconds with decimals.
> HWKAPM-731 : Add duration filter to diagrams

- client/agent-opentracing/src/main/java/org/hawkular/apm/agent/opentracing/OpenTracingManager.java
- client/agent-opentracing/src/main/resources/rules/java/apm-java-net.btm
- client/agent-opentracing/src/main/resources/rules/java/apm-java-sql.btm
- client/agent-opentracing/src/main/resources/rules/javax/apm-javax-servlet.btm
- client/agent-opentracing/src/main/resources/rules/org/apache/apm-apache-http-client.btm
- client/agent-opentracing/src/test/java/org/hawkular/apm/agent/opentracing/OpenTracingManagerTest.java
- client/opentracing/src/main/java/io/opentracing/APMSpan.java
- client/opentracing/src/main/java/io/opentracing/AbstractAPMTracer.java
- dist/pom.xml
- dist/src/main/resources/apm/setenv.sh
- dist/src/main/scripts/distro-assembly.xml
Including script in dist for using opentracing agent, and fixed issues with using parent span vs span context from byteman rules.
> HWKAPM-739 Add JDBC instrumentation rules for OpenTracing java agent.

- api/src/main/java/org/hawkular/apm/api/utils/PropertyUtil.java
- client/trace-publisher-rest-client/src/main/java/org/hawkular/apm/trace/publisher/rest/client/TracePublisherRESTClient.java
- server/rest/pom.xml
- server/rest/src/main/java/org/hawkular/apm/server/rest/TraceHandler.java
- server/rest/src/main/java/org/hawkular/apm/server/rest/filter/CorsFilter.java
- server/war/src/main/webapp/WEB-INF/web.xml
- tests/common/src/main/java/org/hawkular/apm/tests/common/ApmMockServer.java
CORS filter
@objectiser @jpkrohling Could you please review?
> CORS filter

- ui/src/main/scripts/plugins/directives/filter-sidebar/ts/filterSidebarDirective.ts
In order to replicate, both Transactions must have the same property name (eg: `fault`), otherwise it will clear the selected property name and the issue won't occur.
> HWKAPM-742 : Retrieve property values on TX change

- README.md
- client/README.adoc
- examples/README.md
> trivial readme with links to other APM repositories

- api/src/main/java/org/hawkular/apm/api/model/config/ReportingLevel.java
- api/src/main/java/org/hawkular/apm/api/model/trace/ContainerNode.java
- client/api/src/main/java/org/hawkular/apm/client/api/sampler/ContextSampler.java
- client/api/src/main/java/org/hawkular/apm/client/api/sampler/PercentageSampler.java
- client/api/src/main/java/org/hawkular/apm/client/api/sampler/Sampler.java
- client/opentracing/checkstyle-suppression.xml
- client/opentracing/src/main/java/io/opentracing/APMSpan.java
- client/opentracing/src/main/java/io/opentracing/APMSpanBuilder.java
- client/opentracing/src/main/java/io/opentracing/AbstractAPMTracer.java
- client/opentracing/src/main/java/io/opentracing/PropagableState.java
- client/opentracing/src/main/java/org/hawkular/apm/client/opentracing/TraceContext.java
- client/opentracing/src/test/java/org/hawkular/apm/client/opentracing/APMTracerTest.java
- client/opentracing/src/test/java/org/hawkular/apm/client/opentracing/SamplingTest.java
https://issues.jboss.org/browse/HWKAPM-764
> HWKAPM-764 | Percentage sampling

- ui/src/main/scripts/plugins/btm/html/btm.html
- ui/src/main/scripts/plugins/btm/less/hawkular.less
- ui/src/main/scripts/plugins/btm/ts/btm.ts
@objectiser, please review. This is only for the "Managed" tab for now. Merge if you think it's ok and I'll address the others in a different PR or I can add more to this one.
> HWKAPM-628 Integrate Sidebar into Transactions page

- ui/src/main/scripts/plugins/btm/html/btxninfo.html
- ui/src/main/scripts/plugins/btm/ts/btxninfo.ts
@objectiser, please give it a try.
There is some issue that might need to be discussed/solved:
When selecting a fault/property in the charts, it gets added to the filter, but the chart isn't updated to just show that property as before, because in terms of filtering, other values of the same property might be present.
Does it look good to you that way ?
> Integrating filter sidebar into TX Info page

- api/src/main/java/org/hawkular/apm/api/logging/Logger.java
- client/agent-opentracing/src/test/java/org/hawkular/apm/agent/opentracing/TestTraceRecorder.java
- client/api/src/main/java/org/hawkular/apm/client/api/recorder/BatchTraceRecorder.java
- client/api/src/main/java/org/hawkular/apm/client/api/recorder/LoggingRecorder.java
- client/api/src/main/java/org/hawkular/apm/client/api/recorder/TraceRecorder.java
- client/collector/src/main/java/org/hawkular/apm/client/collector/internal/DefaultTraceCollector.java
- client/opentracing/src/main/java/org/hawkular/apm/client/opentracing/EnvironmentAwareTraceRecorder.java
- client/opentracing/src/main/java/org/hawkular/apm/client/opentracing/TraceContext.java
- client/opentracing/src/test/java/org/hawkular/apm/client/opentracing/APMTracerTest.java
@objectiser Could you please look at this? I have slightly changed our `Logger` to be able to programmatically configure it.
> HWKAPM-769 | trace console recorder

- .mvn/srcdeps.yaml
- pom.xml
- server/rest/src/main/java/org/hawkular/apm/server/rest/filter/CorsRequestFilter.java
- server/rest/src/main/java/org/hawkular/apm/server/rest/filter/CorsResponseFilter.java
It means splitting cors filtering into a request filter and a response filter.
Validation is processed during request, adding headers dureing response.
> Use hawkular-commons 0.9.1, update CORS

- client/agent-opentracing/pom.xml
- client/opentracing/pom.xml
- client/opentracing/src/main/java/io/opentracing/impl/APMSpan.java
- client/opentracing/src/main/java/io/opentracing/impl/APMSpanBuilder.java
- client/opentracing/src/main/java/io/opentracing/impl/AbstractAPMTracer.java
- client/opentracing/src/main/java/org/hawkular/apm/client/opentracing/APMTracer.java
- client/opentracing/src/main/java/org/hawkular/apm/client/opentracing/DefaultNodeProcessor.java
- client/opentracing/src/main/java/org/hawkular/apm/client/opentracing/NodeProcessor.java
- client/opentracing/src/main/java/org/hawkular/apm/client/opentracing/TraceContext.java
- client/opentracing/src/test/java/io/opentracing/impl/APMSpanTest.java
- pom.xml
https://issues.jboss.org/browse/HWKAPM-793
> HWKAPM-793 | bump opentracing version to 0.20.4

- ui/src/main/scripts/plugins/e2e/ts/e2e.ts
Also fix sorting, don't toggle ascending/descending at every sort field
change, only change when clicking the same sort field.
> HWKAPM-799 : Sort Instance Details by descending timestamp

- ui/src/main/scripts/plugins/btm/less/hawkular.less
- ui/src/main/scripts/plugins/directives/filter-sidebar/html/filter-sidebar.html
- ui/src/main/scripts/plugins/directives/filter-sidebar/ts/filterSidebarDirective.ts
- ui/src/main/scripts/plugins/e2e/html/e2e.html
- ui/src/main/scripts/plugins/e2e/less/e2e.less
Includes other fixes to better display in mobile.
Sidebar functionality
APM Pages
> HWKAPM-804 : Show sidebar in mobile friendly UI

- pom.xml
@objectiser could you please review? I would like to include this into the next release.
> Bump opentracing version to 0.20.7

- ui/src/main/scripts/plugins/services/ts/services.ts
Show a proper scale on y axis and a label with "No Data Available".
> HWKAPM-842 : Fix Services UI when there's no data

- README.md
Trivial little fix to bring Copyright into current year.
> Update License copyright dates to current year

- ui/src/main/scripts/plugins/services/ts/services.ts
This fills the completion time arrays with timestamps and null value
based on timestamps present in other selected series.
> HWKAPM-858 : Don't draw line on gaps missing data

- ui/src/main/scripts/plugins/services/html/services.html
- ui/src/main/scripts/plugins/services/ts/services.ts
When selecting the "Any" version, all the  named versions are shown, and
new ones will automatically show as well.
> HWKAPM-860 : Services UI support for "Any" buildstamp

- ui/src/main/scripts/plugins/services/html/services.html
Problems
- Labels going outside the screen;
- Card (white area) not occupying all the charts area;
Fixed:
> Fix Services UI card and labels not wrapping
