hawkular/hawkular-apm

feature-pack/standalone/pom.xml, feature-pack/ui-patch/pom.xml, server/cassandra/pom.xml, server/elasticsearch/pom.xml
This adds the relativePath to the feature-pack pom.xml so they are able
to locate the parent when it's not already in the M2 repo.
Also remove dup dependency on jboss-logging-annotations at some pom.xml
=> HWKBTM-323 : Fix first-time build failures

ui/src/main/scripts/plugins/apm/html/apm.html, ui/src/main/scripts/plugins/btm/html/btxnconfig.html, ui/src/main/webapp/index.html
AngularUI version >= 0.14.0 has prefixed their directives with uib-*,
but we are still using 0.13.x so these prefixes do not apply.
Fixing by removing the prefix, but probably to be reverted in the future
when both hawkular and bawkular-btm update to 0.14.x/1.x.
Also removed bootstrap libs incorrectly present in index.html.
=> HWKBTM-315 : Fix AngularUI tags for version < 0.14.0

ui/src/main/scripts/plugins/apm/ts/apmPlugin.ts, ui/src/main/scripts/plugins/btm/ts/btmPlugin.ts
The hawtio plugin modules (APM & BTM) must depend on the  templates
module, "hawkularbtm-templates", so that when they are loaded, templates
are already in the cache and thus not necessary to find them in the FS.
=> HWKBTM-319 : Add modules deps on templates module

ui/src/main/scripts/plugins/apm/ts/apm.ts, ui/src/main/scripts/plugins/btm/ts/btxninfo.ts
In order for angular to recognize and match the values for the select,
they must be a string instead of a number.
=> HWKBTM-318 : Fix empty dropdown in APM & BTxn info

ui/src/main/scripts/plugins/apm/ts/apmPlugin.ts, ui/src/main/scripts/plugins/btm/html/btxninfo.html, ui/src/main/scripts/plugins/btm/ts/btmPlugin.ts
Controllers were being loaded both by the routeProvider and inside the
template. Keeping them only at the template, as Hawtio does in examples.
=> HWKBTM-327 : Instantiate controllers only on page

ui/src/main/scripts/plugins/apm/html/apm.html, ui/src/main/scripts/plugins/apm/ts/apm.ts, ui/src/main/scripts/plugins/btm/html/btxninfo.html, ui/src/main/scripts/plugins/btm/ts/btxninfo.ts
Using the dropdown for pausing/resuming live data was causing digest
cycle issues as the select value was always being changed, triggering a
new cycle, in a loop.
This moves from that approach to using a button for Pausing and Resuming
Live Data, also showing the Last Update time.
=> HWKBTM-300 : Use Pause/Resume for Live Data

ui/src/main/scripts/bower.json, ui/src/main/scripts/plugins/btm/html/btm.html, ui/src/main/scripts/plugins/btm/html/btxncandidates.html, ui/src/main/scripts/plugins/btm/html/btxndisabled.html, ui/src/main/scripts/plugins/btm/html/btxnignored.html, ui/src/main/scripts/plugins/btm/less/main.less, ui/src/main/scripts/plugins/btm/ts/btm.ts, ui/src/main/scripts/plugins/btm/ts/btxndisabled.ts, ui/src/main/scripts/plugins/btm/ts/btxnignored.ts
The hk-url-item CSS class in the console has some remove animation, not
intended to be used in BTM context, replaced the classes -url- by -txn-.
Also fixed the refresh process by having data always available, by only
replacing the data when all of it is gathered.
=> HWKBTM-316 : Fix Active BTxs refresh on console

ui/src/main/scripts/plugins/btm/html/btm.html, ui/src/main/scripts/plugins/btm/ts/btm.ts
This was due to element not being ready at time of the reload, there was
a race condition between DOM element init and ng-init execution.
In the future we should use some form of C3 charts for angular to avoid
manually refreshing.
=> HWKBTM-337 : Fix error loading pie charts

ui/src/main/scripts/plugins/apm/ts/apm.ts, ui/src/main/scripts/plugins/btm/ts/btxninfo.ts
This sets the default Y scale to be 0-10 when there's no data.
=> HWKBTM-362 : Specify default charts Y-scale

ui/src/main/scripts/plugins/btm/html/btxninfo.html
This allows for the faults and properties boxes to be of same height
=> Move BTxn info props dropdown to be right-aligned

ui/src/main/scripts/plugins/btm/html/btxninfo.html, ui/src/main/scripts/plugins/btm/ts/btxninfo.ts
When filtering data (by clicking in the pie chart), colors were being
reset and re-used for different values. With this fix, they now keep the
same color as before filtering.
=> HWKBTM-365 : Keep pie chart colors when filtering

ui/src/main/scripts/plugins/btm/ts/btm.ts
When clicking on Fault Count chart for a specific BTxn, it wasn't
(immediately) leading the user to info page, which only occurred when
a digest cycle happened (could take several seconds). This fixes it by
wrapping it in a $timeout call.
Also took the chance to refactor it to a single function for both charts
=> HWKBTM-382 : Go to BTx Info on click @ Fault Count

ui/src/main/scripts/plugins/btm/html/btm.html, ui/src/main/scripts/plugins/btm/html/btxninfo.html, ui/src/main/scripts/plugins/btm/less/btm.less
- Make "No data" same height (320px) as when there's a chart with data;
- Use flexbox to keep cards at same height at BTxn Info (when there's a
section with data and other without);
- Increase placeholder icon size to make it more similar to chart size;
=> Improve charts spacing and placeholder

ui/src/main/scripts/plugins/apm/html/apm.html, ui/src/main/scripts/plugins/btm/html/btm.html, ui/src/main/scripts/plugins/btm/html/btxninfo.html, ui/src/main/scripts/plugins/btm/less/btm.less
The chart container element must have a min-height to keep the chart
from decreasing indefinitely. This adds a 320px min-height (or 240px in
case of "mobile" size) to the container.
=> HWKBTM-385 : Fix height of chart container element

ui/src/main/scripts/plugins/apm/html/apm.html
With typeahead-editable="false" the ng-model is only updated when the
option is valid. This makes it that while typing, there isn't an update
to the model causing several refreshes with invalid host.
Also removed non-used method calls to selectAction.
=> Fix APM Hostname typeahead, early setting model

ui/src/main/scripts/plugins/directives/dagre-d3/ts/dagreD3Directive.ts
It seems D3 and the directive go out of sync, so the scale is applied
at element draw time and then again at rendering.
The workaround is to remove the applied transformations before rendering
so that it is rendered with default scale and re-apply once rendered.
Also disabled individual node dragging by default, which can be enabled
by using the node-drag attribute on the directive. It suffers from the
same issue, but solving it is a bit more complex, so leaving it out for
now.
=> HWKBTM-414 Fix Pan/Zoom resetting at each refresh

ui/src/main/scripts/plugins/directives/dagre-d3/ts/dagreD3Directive.ts, ui/src/main/scripts/plugins/e2e/less/e2e.less
Force removal of tooltips on graph refresh, otherwise they will stick in
as their trigger element is replaced.
Also added the node id to the tooltip text.
=> HWKBTM-415 : Force tooltip removal on refresh

ui/src/main/scripts/plugins/apm/ts/apm.ts, ui/src/main/scripts/plugins/directives/filter-sidebar/html/filter-sidebar.html, ui/src/main/scripts/plugins/directives/filter-sidebar/ts/filterSidebarDirective.ts, ui/src/main/scripts/plugins/directives/filter-sidebar/ts/filterSidebarPlugin.ts, ui/src/main/scripts/plugins/e2e/ts/e2e.ts
Move common retrieval of filter data (BTxns, Props, Faults, Hosts) to
the sidebar directive instead of individual controllers.
=> Move some common OPs to sidebar directive

ui/src/main/scripts/plugins/templates.js
@ammendonca Thanks Alex for finding the problem and solution.
Issue reported here: https://github.com/tracker1/gulp-header/issues/37
[INFO] [12:10:49] Starting 'template'...
[ERROR] fs.js:839
[ERROR]   return binding.lstat(pathModule._makeLong(path));
[ERROR]                  ^
[ERROR] 
[ERROR] Error: ENOENT: no such file or directory, lstat '/home/gbrown/repositories/hawkular/objectiser/hawkular-apm/ui/target/gulp-build/plugins/templates.js'
[ERROR]     at Error (native)
[ERROR]     at Object.fs.lstatSync (fs.js:839:18)
=> Temporary fix for missing templates.js exception

client/collector/src/main/java/org/hawkular/apm/client/collector/internal/FragmentBuilder.java, client/instrumenter/src/main/java/org/hawkular/apm/instrumenter/rules/CollectorActionTransformer.java, client/instrumenter/src/main/java/org/hawkular/apm/instrumenter/rules/CompleteCorrelationTransformer.java, client/instrumenter/src/main/java/org/hawkular/apm/instrumenter/rules/InitiateCorrelationTransformer.java, client/instrumenter/src/main/java/org/hawkular/apm/instrumenter/rules/ProcessContentTransformer.java, client/instrumenter/src/main/java/org/hawkular/apm/instrumenter/rules/ProcessHeadersTransformer.java, client/instrumenter/src/main/java/org/hawkular/apm/instrumenter/rules/SetBusinessTransactionTransformer.java, client/instrumenter/src/main/java/org/hawkular/apm/instrumenter/rules/SetDetailTransformer.java, client/instrumenter/src/main/java/org/hawkular/apm/instrumenter/rules/SetFaultTransformer.java, client/instrumenter/src/main/java/org/hawkular/apm/instrumenter/rules/SetLevelTransformer.java, client/instrumenter/src/main/java/org/hawkular/apm/instrumenter/rules/SetPrincipalTransformer.java, client/instrumenter/src/main/java/org/hawkular/apm/instrumenter/rules/SetPropertyTransformer.java, client/instrumenter/src/main/java/org/hawkular/apm/instrumenter/rules/SetStateTransformer.java
This pull request is focused on resolving occurrences of Sonar rule
pmd:InsufficientStringBufferDeclaration - "Insufficient String Buffer Declaration".
You can find more information about the issue here:
https://sonar.spring.io/coding_rules#rule_key=pmd:InsufficientStringBufferDeclaration
=> Fixing pmd:InsufficientStringBufferDeclaration - Insufficient String Buffer Declaration

api/src/main/java/org/hawkular/apm/api/services/ConfigurationLoader.java, client/trace-service-rest-client/src/main/java/org/hawkular/apm/trace/service/rest/client/TraceServiceRESTClient.java, tools/instrumenter/src/main/java/org/hawkular/apm/tools/instrumenter/InstrumenterUtil.java
This pull request is focused on resolving occurrences of Sonar rules:
squid:S2095 - "Resources should be closed".
You can find more information about the issue here:
https://sonarqube.com/coding_rules#q=squid:S2095
squid:S2674 - "The value returned from a stream read should be checked".
You can find more information about the issue here:
https://sonarqube.com/coding_rules#q=squid:S2674
=> Fixing squid:S2095, squid:S2674

api/src/main/java/org/hawkular/apm/api/model/trace/Component.java, api/src/main/java/org/hawkular/apm/api/model/trace/Consumer.java, api/src/main/java/org/hawkular/apm/api/model/trace/ContainerNode.java, api/src/main/java/org/hawkular/apm/api/model/trace/InteractionNode.java, api/src/main/java/org/hawkular/apm/api/model/trace/Producer.java, performance/server/src/main/java/org/hawkular/apm/performance/server/ClientSimulator.java
This pull request is focused on resolving occurrences of Sonar rule
squid:S2259 - "Null pointers should not be dereferenced".
You can find more information about the issue here:
https://sonarqube.com/coding_rules#q=squid:S2259
=> Fixing squid:S2259 - Null pointers should not be dereferenced

api/src/main/java/org/hawkular/apm/api/services/AnalyticsService.java, api/src/main/java/org/hawkular/apm/api/services/StoreException.java, api/src/main/java/org/hawkular/apm/api/services/TraceService.java, client/analytics-service-rest-client/src/main/java/org/hawkular/apm/analytics/service/rest/client/AnalyticsServiceRESTClient.java, client/collector/src/test/java/org/hawkular/apm/client/collector/DefaultTraceCollectorTest.java, client/trace-service-rest-client/src/main/java/org/hawkular/apm/trace/service/rest/client/TraceServiceRESTClient.java, processors/communicationdetails-deriver/src/main/java/org/hawkular/apm/processor/communicationdetails/CommunicationDetailsDeriver.java, processors/fragmentcompletiontime-deriver/src/main/java/org/hawkular/apm/processor/fragmentcompletiontime/FragmentCompletionTimeDeriver.java, processors/nodedetails-deriver/src/main/java/org/hawkular/apm/processor/nodedetails/NodeDetailsDeriver.java, processors/notification-deriver/src/main/java/org/hawkular/apm/processor/notification/NotificationDeriver.java, processors/tracecompletiontime-deriver/src/main/java/org/hawkular/apm/processor/tracecompletiontime/TraceCompletionInformationInitiator.java, processors/tracecompletiontime-deriver/src/main/java/org/hawkular/apm/processor/tracecompletiontime/TraceCompletionInformationProcessor.java, processors/tracecompletiontime-deriver/src/main/java/org/hawkular/apm/processor/tracecompletiontime/TraceCompletionTimeDeriver.java, server/api/src/main/java/org/hawkular/apm/server/api/task/AbstractProcessor.java, server/api/src/main/java/org/hawkular/apm/server/api/task/ProcessingUnit.java, server/api/src/main/java/org/hawkular/apm/server/api/task/Processor.java, server/api/src/main/java/org/hawkular/apm/server/api/task/RetryAttemptException.java, server/api/src/test/java/org/hawkular/apm/server/api/task/ProcessingUnitTest.java, server/elasticsearch/src/main/java/org/hawkular/apm/server/elasticsearch/AnalyticsServiceElasticsearch.java, server/elasticsearch/src/main/java/org/hawkular/apm/server/elasticsearch/ElasticsearchClient.java, server/elasticsearch/src/main/java/org/hawkular/apm/server/elasticsearch/TraceServiceElasticsearch.java, server/jms/src/main/java/org/hawkular/apm/server/jms/CommunicationDetailsCacheMDB.java, server/jms/src/main/java/org/hawkular/apm/server/jms/CommunicationDetailsStoreMDB.java, server/jms/src/main/java/org/hawkular/apm/server/jms/FragmentCompletionTimeStoreMDB.java, server/jms/src/main/java/org/hawkular/apm/server/jms/NodeDetailsStoreMDB.java, server/jms/src/main/java/org/hawkular/apm/server/jms/TraceCompletionTimeStoreMDB.java, server/jms/src/main/java/org/hawkular/apm/server/jms/TraceStoreMDB.java
Review notes:
- Added typed exception for both the processor, to trigger the retry, but also on the TraceService and AnalyticsService APIs related to failures when storing information.
=> HWKAPM-485 Use a typed exception for triggering retries

api/src/main/java/org/hawkular/apm/api/internal/actions/helpers/XML.java, api/src/main/java/org/hawkular/apm/api/services/AbstractAnalyticsService.java, api/src/main/java/org/hawkular/apm/api/utils/EndpointUtil.java
This pull request is focused on resolving occurrences of Sonar rule
squid:S1149 - "Synchronized classes Vector, Hashtable, Stack and StringBuffer should not be used".
You can find more information about the issue here:
https://sonar.spring.io/coding_rules#rule_key=squid:S1149
=> Fixing squid:S1149 - Synchronized classes Vector, Hashtable, Stack and StringBuffer should not be used

api/src/main/java/org/hawkular/apm/api/services/AbstractConfigurationService.java, client/analytics-service-rest-client/src/main/java/org/hawkular/apm/analytics/service/rest/client/AnalyticsServiceRESTClient.java, client/collector/src/main/java/org/hawkular/apm/client/collector/DefaultTraceCollector.java, client/instrumenter/src/main/java/org/hawkular/apm/instrumenter/ClientManager.java, client/trace-service-rest-client/src/main/java/org/hawkular/apm/trace/service/rest/client/TraceServiceRESTClient.java, server/elasticsearch/src/main/java/org/hawkular/apm/server/elasticsearch/ElasticsearchClient.java, tools/instrumenter/src/main/java/org/hawkular/apm/tools/instrumenter/InstrumenterUtil.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:S2864 - ""entrySet()" should be iterated when both the key and value are needed".
You can find more information about the issue here: 
https://sonarqube.com/coding_rules#q=squid:S2864
=> Fixing squid:S2864 - "entrySet()" should be iterated when both the key and value are needed

server/api/src/main/java/org/hawkular/apm/server/api/services/SpanService.java, server/elasticsearch/src/main/java/org/hawkular/apm/server/elasticsearch/ElasticsearchClient.java, server/elasticsearch/src/main/java/org/hawkular/apm/server/elasticsearch/SpanServiceElasticsearch.java, server/elasticsearch/src/main/resources/hawkular-apm-mapping.json, server/elasticsearch/src/test/java/org/hawkular/apm/server/elasticsearch/SpanServiceElasticsearchTest.java
https://issues.jboss.org/browse/HWKAPM-525
Review notes:
* `SpanService.store()` takes the same function as `SpanCache` to modify ids of given spans. However, modified ids are not stored in span entity but only as an index.
=> HWKAPM-525 | Span Service and Elasticsearch Impl

ui/src/main/scripts/plugins/e2e/html/details-modal.html
https://issues.jboss.org/browse/HWKAPM-575
Review note: it the text in property span is too long it would still overflow
=> HWKAPM-575 | Instance table display problem when long property field

tests/instrumentation-framework/src/main/java/org/hawkular/apm/tests/dockerized/TestScenarioRunner.java, tests/instrumentation-framework/src/main/java/org/hawkular/apm/tests/dockerized/environment/AbstractDockerBasedEnvironment.java, tests/instrumentation-framework/src/main/java/org/hawkular/apm/tests/dockerized/environment/DockerComposeExecutor.java, tests/instrumentation-framework/src/main/java/org/hawkular/apm/tests/dockerized/environment/DockerImageExecutor.java, tests/instrumentation-framework/src/main/java/org/hawkular/apm/tests/dockerized/environment/TestEnvironmentExecutor.java, tests/instrumentation-framework/src/test/java/org/hawkular/apm/tests/dockerized/InstrumentationTest.java, tests/instrumentation-framework/src/test/resources/testTicketMonsterDockerCompose/docker-compose.yml, tests/instrumentation-framework/src/test/resources/testTicketMonsterDockerCompose/test.json
https://issues.jboss.org/browse/HWKAPM-589
* enables instrumentation framework tests
Review notes: 
please run:
* `docker network rm hawkular-apm`
* `mvn clean install` in instrumentation-framework directory
* `docker network ls` -> there should not be `hawkular-apm` network
=> HWKAPM-589 | Instrumentation test framework failing due to "Address already in use"

api/src/main/java/org/hawkular/apm/api/services/ConfigurationLoader.java
similar error like [link](https://github.com/swagger-api/swagger-codegen/commit/2a5bd0a80ec13644ace353a8c911a2b9ca102b0b)
```
import java.util.regex.Matcher;
import java.io.File;
...
String str = "foo" + File.separator + "bar";
//following will fail
// str.split(File.separator);
//following is OK
str.split(Matcher.quoteReplacement(File.separator));
```
=> fix url seperator error on window

pom.xml
https://issues.jboss.org/browse/HWKAPM-641
tested on:
```
Client:
Version:      1.12.1
API version:  1.24
Go version:   go1.6.3
Git commit:   23cf638
Built:        
OS/Arch:      linux/amd64
Server:
Version:      1.12.1
API version:  1.24
Go version:   go1.6.3
Git commit:   23cf638
Built:        
OS/Arch:      linux/amd64
```
@objectiser could you please review? Could you please run it too?
=> HWKAPM-641 | updated docker client version, for docker > 1.10

ui/src/main/scripts/plugins/directives/dagre-d3/ts/dagreD3Directive.ts
When toggling between initial nodes, there were an invisible string
being added to serviceName, which caused issues later when try to match
the selected node with the one in the list.
This fixes it, doesn't add the character and changes the way lack of
serviceName is displayed.
=> HWKAPM-717 : Fix toggling between initial nodes

ui/src/main/scripts/plugins/e2e/html/details-modal.html, ui/src/main/scripts/plugins/e2e/less/e2e.less
- Fixed some rows width to better use available horizontal space (broke timestamp in two lines, decreased duration and details width);
- Collapse long property values (limit at 16 chars). Toggle between collapsed/expanded with click. Tooltip shows whole value;
- Fixed inline styles to CSS classes;
=> HWKAPM-580 : Instance Details table enhancements

tests/app/polyglot-opentracing/js/index.js, tests/app/polyglot-opentracing/js/package.json
@objectiser could you please review? 
Now it will use fixed versions of JS dependencies.
https://docs.npmjs.com/files/package.json#dependencies
=> itest opentracing polyglot app, JS provider use fixed versions

ui/src/main/scripts/plugins/directives/instance-view-diagram/ts/instanceViewDiagramDirective.ts, ui/src/main/scripts/plugins/e2e/less/e2e.less, ui/src/main/scripts/plugins/e2e/ts/e2e.ts
Some limitations, so the border needs to be in the same color as the severity stripe.
Currently green (severity 0) is for 0-50% of highest duration, gold (severity 1) is for 50%-70%, orange (severity 2) is for 70%-90% and red (severity 3) is for 90-100%.
Some samples:
=> HWKAPM-721 : Show severity in Instance Details Diagram

tests/app/polyglot-opentracing/docker-compose.yml, tests/app/polyglot-opentracing/java/Dockerfile, tests/app/polyglot-opentracing/java/pom.xml, tests/instrumentation-framework/src/main/java/org/hawkular/apm/tests/dockerized/environment/DockerComposeExecutor.java
https://issues.jboss.org/browse/HWKAPM-802
It does not clean base images as java,node. Everything else is removed.
Review notes:
1. `docker rmi -f $(dokcer images -q)`
2. `mvn clean install -Pitest -fn`
3. `docker images` -> It should list only `openjdk` and `node`
run 2. and 3. again it should always show the same images.
=> HWKAPM-802 | Docker images need to be cleaned up after jenkins CI run

ui/src/main/scripts/plugins/directives/instance-view-diagram/ts/instanceViewDiagramDirective.ts, ui/src/main/scripts/plugins/e2e/less/e2e.less
Show a warning sign on the bottom right for nodes that have a fault property.
(Sample image has all nodes with the marker, for viewing how it looks in the different node types)
=> HWKAPM-785 : Highlight Instance nodes with faults

client/agent-opentracing/src/main/java/org/hawkular/apm/agent/opentracing/OpenTracingManager.java
Added to better understand what's going on.
Now I understand why requests to java server pages are ignored.
If you prefer 'finest' let me know.
=> log skipped paths

client/agent-opentracing/src/main/java/org/hawkular/apm/agent/opentracing/OpenTracingRuleLoader.java
Without this patch this happens:
```
Starting foo: Exception in thread "main" java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at …
```
=> dont fail the jvm when one of the btm files is corrupt

api/src/main/java/org/hawkular/apm/api/utils/PropertyUtil.java, client/agent-opentracing/src/main/java/org/hawkular/apm/agent/opentracing/OpenTracingManager.java, client/agent-opentracing/src/test/java/org/hawkular/apm/agent/opentracing/OpenTracingManagerTest.java
primarily made to allow tracing of jsp files - if you think my commit is overengineered I could refactor to a simple `path.endswith(".jsp")` check
=> allow whitelisting of file extensions for includePath logic

examples/vertx-opentracing/pom.xml, performance/server/pom.xml, tests/pom.xml
https://issues.jboss.org/browse/HWKAPM-815
maven-deploy-plugin should prevent publishing unnecessary artifacts to maven central repo.
=> HWKAPM-815 | Do not publish test and example artifacts to maven

.travis.yml
Based on the build status it looks like sometimes the build will fail with really long time while fetching ui libraries.
This can be avoided by enabling travis cache on libraries
* Bower's libs (location - `ui/target/gulp-build/libs`)
* Node modules (location - `ui/target/gulp-build/node_modules`)
=> Add cache for bower libs and node_packages

client/opentracing/src/main/java/io/opentracing/impl/AbstractAPMTracer.java
This enables to use Format.Bultin.HTTP_HEADERS.
Previously only Format.Builtin.TEXT_MAP was registered.
@objectiser could you please review? I will need this for WF fraction. Could we do a micro release?
=> Register HTTP extractor/injector

ui/src/main/scripts/plugins/apm/html/apm.html, ui/src/main/scripts/plugins/btm/html/btm.html, ui/src/main/scripts/plugins/btm/html/btxnconfig.html, ui/src/main/scripts/plugins/btm/html/btxnignored.html, ui/src/main/scripts/plugins/directives/dagre-d3/ts/dagreD3Directive.ts, ui/src/main/scripts/plugins/directives/filter-sidebar/html/filter-sidebar.html, ui/src/main/scripts/plugins/directives/instance-view-diagram/ts/instanceViewDiagramDirective.ts, ui/src/main/scripts/plugins/e2e/html/details-modal.html, ui/src/main/scripts/plugins/e2e/ts/e2e.ts
While navigating the page, multiple warnings are visible in the browser console due to using old style directives (not namespaced with uib-), this fixes it.
@objectiser please have a look at the whole page, and see if everything is working properly and no warnings are shown. I've done it myself, but better double check.
=> Fix Bootstrap UI warnings, using uib-* directives

client/api/src/main/java/org/hawkular/apm/client/api/recorder/BatchTraceRecorder.java, client/collector/src/test/java/org/hawkular/apm/client/collector/internal/DefaultTraceCollectorTest.java
This would make the `HAWKULAR_APM_TENANT_ID` environment variable consistent with other references.
=> Fix HAWKULAR_APM_TENANT_ID env variable
